### ISSUE TITLE
ARM64: 128bit int literal is only showing bottom 64bit

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2168]
**Describe the bug**
128bits are loaded via `ldr q0, [x3]` but ghidra only displays 64 bits

**To Reproduce**
1. Decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/arm64_various_simd/arm64_elf/subject.exe

**Expected behavior**
Output should look like
```
undefined8 cmp_bytes(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3)

{
  undefined8 uVar1;
  undefined auVar2 [16];
  
  auVar2 = NEON_cmeq((undefined  [16])0x73207369204d55535069206d65526f4c,(undefined  [16])0x73207369206d75737049206d65726f4c,1);
...
```

It currently is:
```
undefined8 cmp_bytes(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3)

{
  undefined8 uVar1;
  undefined auVar2 [16];
  
  auVar2 = NEON_cmeq((undefined  [16])0x5069206d65526f4c,(undefined  [16])0x7049206d65726f4c,1);
```

Assembler:
```
cmp_bytes:
     bb8:	03 00 00 90 	adrp	x3, #0
     bbc:	63 e0 37 91 	add	x3, x3, #3576
     bc0:	04 00 00 90 	adrp	x4, #0
     bc4:	84 c0 38 91 	add	x4, x4, #3632
     bc8:	60 00 c0 3d 	ldr	q0, [x3]
     bcc:	81 00 c0 3d 	ldr	q1, [x4]
     bd0:	20 8c 20 6e 	cmeq	v0.16b, v1.16b, v0.16b
     bd4:	40 00 80 3d 	str	q0, [x2]
     bd8:	03 00 ae 9e 	fmov	x3, v0.d[1]
     bdc:	03 00 00 f9 	str	x3, [x0]
     be0:	03 00 66 9e 	fmov	x3, d0
     be4:	23 00 00 f9 	str	x3, [x1]
     be8:	e0 03 1f aa 	mov	x0, xzr
     bec:	c0 03 5f d6 	ret
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC
